project_id = "pos-system"

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]


[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600

[storage]
file_size_limit = "50MiB"


