name: Apply DB Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          access-token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Supabase login
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # Push migrations via management API (no DB password needed)
      - name: Push migrations to remote
        run: supabase db push --project-ref $SUPABASE_PROJECT_REF --include-all
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

      # Option B (fallback): If your setup requires a DB URL/password, uncomment below and set DATABASE_URL in secrets
      # - name: Push with DB URL
      #   run: supabase db push --db-url "${{ secrets.DATABASE_URL }}"


