name: Apply DB Migrations

on:
  push:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF --access-token $SUPABASE_ACCESS_TOKEN
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # Option A: Push migrations via management API (preferred; no DB URL needed)
      - name: Push migrations to remote
        run: supabase db push --include-all

      # Option B (fallback): If your setup requires a DB URL/password, uncomment below and set DATABASE_URL in secrets
      # - name: Push with DB URL
      #   run: supabase db push --db-url "${{ secrets.DATABASE_URL }}"


